name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (or ECR)
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push api Docker image
        run: |
          docker build -t api ./api
          docker tag api 517860088618.dkr.ecr.us-west-2.amazonaws.com/mediscribe:api
          docker push 517860088618.dkr.ecr.us-west-2.amazonaws.com/mediscribe:api

      # - name: Build and push ai Docker image
      #   run: |
      #     docker build -t ai ./service2
      #     docker tag ai 517860088618.dkr.ecr.us-west-2.amazonaws.com/mediscribe:ai
      #     docker push 517860088618.dkr.ecr.us-west-2.amazonaws.com/mediscribe:ai

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            docker pull 517860088618.dkr.ecr.us-west-2.amazonaws.com/mediscribe:api
            # docker pull 517860088618.dkr.ecr.us-west-2.amazonaws.com/mediscribe:ai
            docker-compose -f /home/${{ secrets.EC2_USER }}/docker-compose.yml up -d
