name: Deploy to EC2

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to AWS ECR
        run: aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 517860088618.dkr.ecr.us-west-2.amazonaws.com

      - name: Build and push api Docker image
        run: |
          docker build -t api ./api
          docker tag api 517860088618.dkr.ecr.us-west-2.amazonaws.com/mediscribe:api
          docker push 517860088618.dkr.ecr.us-west-2.amazonaws.com/mediscribe:api

      # - name: Build and push ai Docker image
      #   run: |
      #     docker build -t ai ./service2
      #     docker tag ai 517860088618.dkr.ecr.us-west-2.amazonaws.com/mediscribe:ai
      #     docker push 517860088618.dkr.ecr.us-west-2.amazonaws.com/mediscribe:ai

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install AWS CLI if not already installed
            if ! command -v aws &> /dev/null
            then
              echo "AWS CLI not found. Installing..."
              sudo apt-get update
              sudo apt-get install -y awscli
            fi

            # Pull the Docker image from ECR
            docker pull 517860088618.dkr.ecr.us-west-2.amazonaws.com/mediscribe:api

            # Start containers using docker-compose
            docker-compose -f /home/${{ secrets.EC2_USER }}/docker-compose.yml up -d
