name: Deploy to EC2

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Authenticate to AWS ECR
        run: docker login -u AWS -p $(aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }}) 517860088618.dkr.ecr.us-west-2.amazonaws.com

      - name: Build and push api Docker image
        run: |
          docker build -t api ./api
          docker tag api 517860088618.dkr.ecr.us-west-2.amazonaws.com/mediscribe:api
          docker push 517860088618.dkr.ecr.us-west-2.amazonaws.com/mediscribe:api

      # Uncomment if you're also deploying the "ai" Docker image
      # - name: Build and push ai Docker image
      #   run: |
      #     docker build -t ai ./service2
      #     docker tag ai 517860088618.dkr.ecr.us-west-2.amazonaws.com/mediscribe:ai
      #     docker push 517860088618.dkr.ecr.us-west-2.amazonaws.com/mediscribe:ai

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install Docker if it's not already installed
            if ! command -v docker &> /dev/null
            then
              echo "Docker not found. Installing Docker..."
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl enable --now docker
            fi

            # Install Docker Compose if not already installed
            if ! command -v docker-compose &> /dev/null
            then
              echo "Docker Compose not found. Installing Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Login to ECR and pull the Docker image
            aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 517860088618.dkr.ecr.us-west-2.amazonaws.com
            docker pull 517860088618.dkr.ecr.us-west-2.amazonaws.com/mediscribe:api

            # Pull the latest Docker images and restart containers with Docker Compose
            cd /home/${{ secrets.EC2_USER }}
            docker-compose pull
            docker-compose up -d --remove-orphans

            # Optionally, clean up unused Docker images
            docker system prune -f
